# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 21:39
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='metadata')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date and time of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date and time of last update')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('location', models.CharField(max_length=64, verbose_name='location')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('available_from', models.DateTimeField(default=datetime.datetime(2017, 5, 5, 6, 0, 0, 866578, tzinfo=utc), verbose_name='available from')),
                ('available_until', models.DateTimeField(default=datetime.datetime(2017, 5, 5, 21, 0, 0, 866638, tzinfo=utc), verbose_name='available until')),
                ('supplies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=['Proyector', 'Pizarr\xf3n'], size=None, verbose_name='supplies')),
            ],
            options={
                'verbose_name': 'meeting room',
                'verbose_name_plural': 'meeting rooms',
            },
        ),
    ]
