# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 18:04
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings_management', '0004_auto_20170505_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomreservation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='reservation confirmed'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 6, 0, 0, 337555, tzinfo=utc), verbose_name='available from'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 21, 0, 0, 337617, tzinfo=utc), verbose_name='available until'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='supplies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=['Proyector', 'Pizarr\xf3n'], help_text='Add supplies separated by comma', size=None, verbose_name='supplies'),
        ),
        migrations.AlterField(
            model_name='meetingroomrequest',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='meetings_management.MeetingRoomUser'),
        ),
    ]
