# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings_management', '0005_auto_20170509_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomrequest',
            name='user',
            field=models.ForeignKey(default='02b3a7f3-744b-407f-b4fd-5d3f9ecb0318', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='meetings_management.MeetingRoomUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 6, 0, 0, 421087, tzinfo=utc), verbose_name='available from'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 21, 0, 0, 421149, tzinfo=utc), verbose_name='available until'),
        ),
        migrations.AlterField(
            model_name='meetingroomrequest',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_request_user', to='meetings_management.MeetingRoomUser'),
        ),
    ]
