# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings_management', '0006_auto_20170509_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroomrequest',
            name='room',
        ),
        migrations.AddField(
            model_name='meetingroomrequest',
            name='reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meetings_management.MeetingRoomReservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroomrequest',
            name='reserved_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 18, 47, 6, 519646, tzinfo=utc), verbose_name='need to reserve from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroomrequest',
            name='reserved_until',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 18, 47, 13, 840383, tzinfo=utc), verbose_name='need to reserve until'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 6, 0, 0, 546707, tzinfo=utc), verbose_name='available from'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 21, 0, 0, 546776, tzinfo=utc), verbose_name='available until'),
        ),
    ]
