# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings_management', '0007_auto_20170510_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 6, 0, 0, 169174, tzinfo=utc), verbose_name='available from'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 21, 0, 0, 169243, tzinfo=utc), verbose_name='available until'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingroomrequest',
            unique_together=set([('to_user', 'reservation')]),
        ),
    ]
